# Generated by Django 5.1.4 on 2024-12-28 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_logged_in_before',
            field=models.BooleanField(default=False),
        ),
    ]
