# Generated by Django 5.1.4 on 2024-12-28 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_has_logged_in_before'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='has_logged_in_before',
            new_name='has_reset_password',
        ),
    ]
