# Generated by Django 5.1.4 on 2024-12-29 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_has_logged_in_before_user_has_reset_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='id',
            field=models.PositiveSmallIntegerField(choices=[(1, 'student'), (2, 'teacher'), (3, 'secretary'), (4, 'superuser'), (5, 'staff'), (6, 'guardian')], primary_key=True, serialize=False),
        ),
    ]
