# Generated by Django 5.1.4 on 2024-12-29 21:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='id',
            field=models.PositiveSmallIntegerField(choices=[(1, 'طالب'), (2, 'معلم'), (3, 'سكرتير'), (4, 'مشرف عام'), (5, 'موظف'), (6, 'ولي أمر')], primary_key=True, serialize=False, verbose_name='الدور'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الانضمام'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='عنوان البريد الإلكتروني'),
        ),
        migrations.AlterField(
            model_name='user',
            name='has_reset_password',
            field=models.BooleanField(default=False, verbose_name='تغيير كلمة المرور'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='عضو فريق العمل'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='مشرف عام'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='الاسم الكامل'),
        ),
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(to='users.role', verbose_name='الأدوار'),
        ),
    ]
