# Generated by Django 5.1.4 on 2024-12-31 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_role_id_alter_user_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'مستخدم', 'verbose_name_plural': 'المستخدمين'},
        ),
    ]
