# Generated by Django 5.1.4 on 2024-12-27 22:09

import django.db.models.deletion
import utils.funcs
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0001_initial'),
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم ولي الأمر')),
                ('image', models.ImageField(blank=True, null=True, upload_to=utils.funcs.upload_file, verbose_name='صورة ولي الأمر')),
                ('address', models.TextField(blank=True, null=True, verbose_name='عنوان ولي الأمر')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني')),
                ('nationality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utils.nationality', verbose_name='الجنسية')),
                ('religion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utils.religion', verbose_name='الديانة')),
            ],
            options={
                'verbose_name': 'ولي الأمر',
                'verbose_name_plural': 'أولياء الأمور',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم الطالب')),
                ('address', models.TextField(blank=True, null=True, verbose_name='عنوان الطالب')),
                ('gender', models.CharField(blank=True, choices=[('male', 'ذكر'), ('female', 'أنثى')], default='male', max_length=6, verbose_name='نوع الطالب')),
                ('place_of_birth', models.CharField(max_length=100, verbose_name='مكان الميلاد')),
                ('birth_date', models.DateField(verbose_name='تاريخ الميلاد')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف')),
                ('image', models.ImageField(blank=True, null=True, upload_to=utils.funcs.upload_file, verbose_name='صورة الطالب')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني')),
                ('nationality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utils.nationality', verbose_name='الجنسية')),
                ('religion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utils.religion', verbose_name='الديانة')),
            ],
            options={
                'verbose_name': 'طالب',
                'verbose_name_plural': 'الطلاب',
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=utils.funcs.upload_file, verbose_name='ملف المرفق')),
                ('label', models.CharField(max_length=255, verbose_name='تسمية المرفق')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف المرفق')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'مرفق',
                'verbose_name_plural': 'المرفقات',
            },
        ),
        migrations.CreateModel(
            name='StudentGuardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(choices=[('father', 'أب'), ('mother', 'أم'), ('grandfather', 'جد'), ('grandmother', 'جدة'), ('uncle', 'عم'), ('aunt', 'عمة'), ('brother', 'أخ'), ('sister', 'أخت'), ('other', 'أخرى')], max_length=15, verbose_name='صلة القرابة')),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.guardian', verbose_name='ولي الأمر')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student', verbose_name='الطالب')),
            ],
            options={
                'unique_together': {('student', 'guardian')},
            },
        ),
        migrations.CreateModel(
            name='StudentSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.academicyear', verbose_name='السنة الأكاديمية')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.section', verbose_name='الشعبة')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student', verbose_name='الطالب')),
            ],
            options={
                'unique_together': {('student', 'section', 'academic_year')},
            },
        ),
    ]
