# Generated by Django 5.1.4 on 2024-12-29 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_guardian_email_alter_student_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsection',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_section', to='students.student', verbose_name='الطالب'),
        ),
    ]
