# Generated by Django 5.1.4 on 2024-12-29 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
        ('students', '0005_alter_studentsection_student'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentsection',
            unique_together={('student', 'academic_year')},
        ),
    ]
