# Generated by Django 5.1.4 on 2024-12-27 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=9, unique=True, verbose_name='السنة الأكاديمية')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='تاريخ بداية السنة')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ نهاية السنة')),
                ('is_current', models.BooleanField(default=False, verbose_name='السنة الحالية')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف السنة')),
            ],
            options={
                'verbose_name': 'سنة أكاديمية',
                'verbose_name_plural': 'السنوات الأكاديمية',
            },
        ),
        migrations.CreateModel(
            name='ClassLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, unique=True, verbose_name='اسم الصف الدراسي')),
                ('stage', models.CharField(choices=[('kindergarten', 'رياض الأطفال'), ('primary', 'المرحلة الابتدائية'), ('middle', 'المرحلة الإعدادية'), ('secondary', 'المرحلة الثانوية')], max_length=50, verbose_name='المستوى الدراسي')),
            ],
            options={
                'verbose_name': 'صف دراسي',
                'verbose_name_plural': 'الصفوف الدراسية',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='اسم الشعبة')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.academicyear', verbose_name='السنة الأكاديمية')),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.classlevel', verbose_name='الصف الدراسي')),
            ],
            options={
                'verbose_name': 'شعبة',
                'verbose_name_plural': 'الشعب',
                'unique_together': {('name', 'class_level', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='اسم المادة الدراسية')),
                ('semester', models.CharField(choices=[('first_semester', 'الفصل الاول'), ('second_semester', 'الفصل الثاني')], max_length=50, verbose_name='الفصل الدراسي')),
                ('note', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.classlevel', verbose_name='الصف')),
            ],
            options={
                'verbose_name': 'مادة دراسية',
                'verbose_name_plural': 'المواد الدراسية',
                'unique_together': {('name', 'class_level', 'semester')},
            },
        ),
    ]
