# Generated by Django 5.1.4 on 2024-12-28 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0002_alter_academicday_options_alter_attendance_options'),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='school.section', verbose_name='الشعبة'),
            preserve_default=False,
        ),
    ]
