# Generated by Django 5.1.4 on 2024-12-29 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0004_alter_attendance_section'),
        ('school', '0001_initial'),
        ('students', '0006_alter_studentsection_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'academic_day', 'section')},
        ),
    ]
