# Generated by Django 5.1.4 on 2024-12-27 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم الامتحان')),
                ('min_value', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='الحد الأدنى للعلامة')),
                ('max_value', models.DecimalField(decimal_places=2, default=50, max_digits=4, verbose_name='الحد الأقصى للعلامة')),
                ('passing_score', models.DecimalField(decimal_places=2, default=25, max_digits=4, verbose_name='علامة النجاح')),
                ('date', models.DateField(verbose_name='تاريخ الامتحان')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.academicyear', verbose_name='السنة الدراسية')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.section', verbose_name='الشعبة')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.subject', verbose_name='المادة ')),
            ],
            options={
                'verbose_name': 'امتحان',
                'verbose_name_plural': 'الامتحانات',
                'unique_together': {('subject', 'section', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='StudentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='الدرجة')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.exam', verbose_name='الامتحان')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'نتائج الامتحان',
                'verbose_name_plural': 'نتائج الامتحان',
                'unique_together': {('student', 'exam')},
            },
        ),
    ]
