# Generated by Django 5.1.4 on 2024-12-27 22:10

import django.db.models.deletion
import utils.funcs
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0001_initial'),
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم المعلم')),
                ('address', models.CharField(blank=True, max_length=150, null=True, verbose_name='عنوان المعلم')),
                ('gender', models.CharField(blank=True, choices=[('male', 'ذكر'), ('female', 'أنثى')], default='male', max_length=10, verbose_name='نوع المعلم')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف')),
                ('image', models.ImageField(blank=True, null=True, upload_to=utils.funcs.upload_file, verbose_name='صورة المعلم')),
                ('nationality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utils.nationality', verbose_name='الجنسية')),
                ('religion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utils.religion', verbose_name='الديانة')),
                ('specialization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utils.specialization', verbose_name='التخصص')),
            ],
            options={
                'verbose_name': 'معلم',
                'verbose_name_plural': 'المعلمين',
            },
        ),
        migrations.CreateModel(
            name='TeacherSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.academicyear', verbose_name='السنة الأكاديمية')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.section', verbose_name='الشعبة')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.subject', verbose_name='المادة')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher', verbose_name='المعلم')),
            ],
            options={
                'verbose_name': 'مادة معلم',
                'verbose_name_plural': 'مواد المعلمين',
                'unique_together': {('teacher', 'subject', 'section', 'academic_year')},
            },
        ),
    ]
